GET http://localhost:8080/api/health
Content-Type: application/json

###

POST http://localhost:8080/routes
Content-Type: application/json

{
  "route": "http://localhost:8080"
}

###
GET http://localhost:8080/health
Accept: application/json

###

DELETE http://localhost:8080/routes
Content-Type: application/json

{
  "route": "http://google.com"
}

###

GET http://localhost:8080/routes
Accept: application/json

###